# Generated by Django 5.2.6 on 2026-03-16 07:44

import django.utils.timezone
import shared.projects.models
import system.utils.file_validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_name', models.CharField(blank=True, help_text='Optional name if evaluator is not a system user', max_length=255, null=True)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('evaluation_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('attainment_of_objectives', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('time_management', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('resource_persons_facilitators', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('topics', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('training_venue', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('food', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('materials_handouts', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('trainings_seminars_overall', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('held_as_scheduled', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('answers_present_need', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('timeliness_overall', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('estimated_events', models.PositiveIntegerField()),
                ('event_progress', models.PositiveIntegerField(default=0)),
                ('estimated_trainees', models.PositiveIntegerField()),
                ('total_trained_individuals', models.PositiveIntegerField(default=0)),
                ('primary_beneficiary', models.CharField(max_length=255)),
                ('primary_location', models.CharField(max_length=255)),
                ('logistics_type', models.CharField(choices=[('BOTH', 'Both'), ('EXTERNAL', 'External'), ('INTERNAL', 'Internal')], max_length=10)),
                ('internal_budget', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('external_budget', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('sponsor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField()),
                ('estimated_end_date', models.DateField()),
                ('used_budget', models.DecimalField(decimal_places=2, default=0, help_text='Amount of the budget that has been spent.', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled')], default='NOT_STARTED', max_length=20)),
                ('has_final_submission', models.BooleanField(default=False, help_text='True when a final submission type has been approved')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(blank=True, max_length=10)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='project_thumbnails/')),
                ('file', models.FileField(upload_to=shared.projects.models.project_document_upload_to)),
                ('document_type', models.CharField(choices=[('PROPOSAL', 'Proposal'), ('ADDITIONAL', 'Additional')], max_length=12)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField()),
                ('rating', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=shared.projects.models.project_event_image_upload_to, validators=[system.utils.file_validators.validate_image_size])),
                ('placeholder', models.BooleanField(default=False)),
                ('has_submission', models.BooleanField(default=False)),
                ('allocated_budget', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Budget allocated for this activity', max_digits=12, null=True)),
                ('evaluation_token', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='Unique token for public evaluation access', null=True, unique=True)),
                ('evaluation_enabled', models.BooleanField(default=True, help_text='Allow public evaluations for this activity')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_incurred', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('expense_date', models.DateField()),
                ('receipt_img', models.ImageField(blank=True, null=True, upload_to='project_expense_receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
                ('viewed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SustainableDevelopmentGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
