# Generated by Django 5.2.6 on 2026-03-16 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0002_initial'),
        ('projects', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevaluation',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='agenda.agenda'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='project_leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='providers',
            field=models.ManyToManyField(related_name='member_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='additional_documents',
            field=models.ManyToManyField(blank=True, related_name='additional_for_projects', to='projects.projectdocument'),
        ),
        migrations.AddField(
            model_name='project',
            name='proposal_document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_for_project', to='projects.projectdocument'),
        ),
        migrations.AddField(
            model_name='projectevaluation',
            name='evaluated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectevaluation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectevent',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectevent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectevent',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_project_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityevaluation',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='projects.projectevent'),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Optional: Link expense to a specific activity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='projects.projectevent'),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectexpenses',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectexpenses',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_expenses', to='projects.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.projecttype'),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.submission'),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sustainabledevelopmentgoal',
            index=models.Index(fields=['goal_number'], name='sdg_goal_number_idx'),
        ),
        migrations.AddField(
            model_name='project',
            name='sdgs',
            field=models.ManyToManyField(related_name='projects', to='projects.sustainabledevelopmentgoal'),
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['project', 'document_type', 'uploaded_at'], name='project_docs_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['project', 'uploaded_at'], name='project_docs_date_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['document_type', 'uploaded_at'], name='docs_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='projectevaluation',
            index=models.Index(fields=['project', '-created_at'], name='proj_eval_proj_date_idx'),
        ),
        migrations.AddIndex(
            model_name='projectevaluation',
            index=models.Index(fields=['evaluated_by', '-created_at'], name='proj_eval_user_idx'),
        ),
        migrations.AddIndex(
            model_name='projectevaluation',
            index=models.Index(fields=['project', 'rating'], name='proj_eval_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='projectevent',
            index=models.Index(fields=['status', 'datetime'], name='proj_evt_sched_date_idx'),
        ),
        migrations.AddIndex(
            model_name='projectevent',
            index=models.Index(fields=['project', '-datetime', '-created_at'], name='proj_evt_timeline_idx'),
        ),
        migrations.AddIndex(
            model_name='projectevent',
            index=models.Index(fields=['project', 'status', '-datetime'], name='proj_evt_proj_status_idx'),
        ),
        migrations.AddIndex(
            model_name='projectevent',
            index=models.Index(fields=['-datetime'], name='proj_evt_datetime_idx'),
        ),
        migrations.AddIndex(
            model_name='projectevent',
            index=models.Index(fields=['placeholder', '-datetime'], name='proj_evt_placeholder_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevaluation',
            index=models.Index(fields=['activity', '-evaluation_date'], name='act_eval_act_date_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevaluation',
            index=models.Index(fields=['evaluated_by', '-evaluation_date'], name='act_eval_user_idx'),
        ),
        migrations.AddIndex(
            model_name='projectexpenses',
            index=models.Index(fields=['project', '-expense_date'], name='proj_exp_proj_date_idx'),
        ),
        migrations.AddIndex(
            model_name='projectexpenses',
            index=models.Index(fields=['-expense_date'], name='proj_exp_date_idx'),
        ),
        migrations.AddIndex(
            model_name='projectupdate',
            index=models.Index(fields=['user', 'viewed', '-updated_at'], name='proj_upd_user_view_idx'),
        ),
        migrations.AddIndex(
            model_name='projectupdate',
            index=models.Index(fields=['project', '-updated_at'], name='proj_upd_proj_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectupdate',
            unique_together={('user', 'project', 'submission', 'status')},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'start_date'], name='proj_status_start_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'estimated_end_date', 'has_final_submission'], name='proj_completion_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', '-created_at'], name='proj_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-created_at'], name='proj_created_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_leader', 'status'], name='proj_leader_status_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['agenda', 'status'], name='proj_agenda_status_idx'),
        ),
    ]
