# Generated by Django 5.2.6 on 2026-03-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('primary_location', models.CharField(max_length=200)),
                ('primary_beneficiary', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('letter_of_intent', models.FileField(blank=True, null=True, upload_to='client_requests/letters_of_intent/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('review_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('endorsed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ENDORSED', 'Endorsed'), ('DENIED', 'Denied')], max_length=50)),
            ],
            options={
                'verbose_name': 'Client Request',
                'verbose_name_plural': 'Client Requests',
            },
        ),
        migrations.CreateModel(
            name='RequestUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
                ('viewed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
