# Generated by Django 5.2.6 on 2026-03-16 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('request', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='endorsed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endorsed_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestupdate',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.clientrequest'),
        ),
        migrations.AddField(
            model_name='requestupdate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='clientrequest',
            index=models.Index(fields=['status', '-submitted_at'], name='req_status_submit_idx'),
        ),
        migrations.AddIndex(
            model_name='clientrequest',
            index=models.Index(fields=['submitted_by', '-submitted_at'], name='req_submitter_idx'),
        ),
        migrations.AddIndex(
            model_name='clientrequest',
            index=models.Index(fields=['status', 'reviewed_by'], name='req_review_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='clientrequest',
            index=models.Index(fields=['status', 'endorsed_at'], name='req_endorsed_idx'),
        ),
        migrations.AddIndex(
            model_name='clientrequest',
            index=models.Index(fields=['submitted_at'], name='req_submitted_date_idx'),
        ),
        migrations.AddIndex(
            model_name='clientrequest',
            index=models.Index(fields=['updated_at', 'status'], name='req_updated_status_idx'),
        ),
        migrations.AddIndex(
            model_name='clientrequest',
            index=models.Index(fields=['organization'], name='req_org_idx'),
        ),
        migrations.AddIndex(
            model_name='requestupdate',
            index=models.Index(fields=['user', '-updated_at'], name='req_upd_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='requestupdate',
            index=models.Index(fields=['user', 'request', 'viewed'], name='req_upd_unread_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='requestupdate',
            unique_together={('user', 'request', 'status')},
        ),
    ]
