# Generated by Django 5.2.6 on 2026-03-16 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rest_framework_api_key', '0005_auto_20220110_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('key', models.CharField(help_text="The unique identifier for the setting (e.g., 'site_name')", max_length=100, primary_key=True, serialize=False, unique=True)),
                ('value', models.TextField(blank=True, help_text='The value of the setting.')),
                ('description', models.CharField(blank=True, help_text='A brief description of what this setting does.', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='APIConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the system or user connecting.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Reason for connection or system details.')),
                ('full_api_key_string', models.CharField(blank=True, help_text='The visible API key string for the user.', max_length=255, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection.', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('DISCONNECTED', 'Disconnected'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('tier', models.CharField(choices=[('TIER_1', 'Tier 1: Projects Read-Only'), ('TIER_2', 'Tier 2: Read All APIs'), ('TIER_3', 'Tier 3: Full Access')], default='TIER_1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_framework_api_key.apikey')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
