# Generated by Django 5.2.6 on 2026-03-16 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0001_initial'),
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budgethistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='budgetpool',
            unique_together={('fiscal_year',)},
        ),
        migrations.AddField(
            model_name='collegebudget',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='college_budget_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collegebudget',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.college'),
        ),
        migrations.AddField(
            model_name='budgethistory',
            name='college_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.collegebudget'),
        ),
        migrations.AddField(
            model_name='externalfunding',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='externalfunding',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='budgethistory',
            name='external_funding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.externalfunding'),
        ),
        migrations.AddIndex(
            model_name='collegebudget',
            index=models.Index(fields=['college', 'status', 'fiscal_year'], name='colbud_col_stat_yr_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collegebudget',
            unique_together={('college', 'fiscal_year')},
        ),
        migrations.AddIndex(
            model_name='externalfunding',
            index=models.Index(fields=['project', 'status'], name='extfund_proj_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='externalfunding',
            index=models.Index(fields=['status', '-proposal_date'], name='extfund_stat_date_idx'),
        ),
        migrations.AddIndex(
            model_name='budgethistory',
            index=models.Index(fields=['college_budget', '-timestamp'], name='budhist_colbud_time_idx'),
        ),
        migrations.AddIndex(
            model_name='budgethistory',
            index=models.Index(fields=['external_funding', '-timestamp'], name='budhist_fund_time_idx'),
        ),
    ]
