# Generated by Django 5.2.6 on 2026-03-16 07:44

import system.utils.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='submissions/files/', validators=[system.utils.file_validators.validate_file_size])),
                ('for_product_production', models.BooleanField(default=False)),
                ('for_research', models.BooleanField(default=False)),
                ('for_extension', models.BooleanField(default=False)),
                ('num_trained_individuals', models.PositiveIntegerField(blank=True, null=True)),
                ('image_event', models.ImageField(blank=True, null=True, upload_to='submissions/event_images/', validators=[system.utils.file_validators.validate_image_size])),
                ('image_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted to College Coordinator'), ('REVISION_REQUESTED', 'Revision Requested'), ('FORWARDED', 'Forwarded to UESO'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=32)),
                ('revision_count', models.PositiveIntegerField(default=0)),
                ('rejection_count', models.PositiveIntegerField(default=0)),
                ('is_late_submission', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reason_for_revision', models.TextField(blank=True, null=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('reason_for_rejection', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
            },
        ),
        migrations.CreateModel(
            name='SubmissionUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
                ('viewed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
