# Generated by Django 5.2.6 on 2026-03-16 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('downloadables', '0002_initial'),
        ('projects', '0002_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_approved_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='downloadable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='downloadables.downloadable'),
        ),
        migrations.AddField(
            model_name='submission',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='projects.projectevent'),
        ),
        migrations.AddField(
            model_name='submission',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='projects.project'),
        ),
        migrations.AddField(
            model_name='submission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissionupdate',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.submission'),
        ),
        migrations.AddField(
            model_name='submissionupdate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', '-deadline'], name='sub_status_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['-deadline'], name='sub_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['project', 'status'], name='sub_project_status_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['downloadable', 'status'], name='sub_form_status_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['project', '-created_at'], name='sub_project_created_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['submitted_at', 'status'], name='sub_submitted_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', 'event'], name='sub_status_event_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['is_late_submission', 'status'], name='sub_late_status_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', 'reviewed_at'], name='sub_review_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionupdate',
            index=models.Index(fields=['user', 'viewed', '-updated_at'], name='subupd_user_view_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionupdate',
            index=models.Index(fields=['submission', '-updated_at'], name='subupd_sub_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submissionupdate',
            unique_together={('user', 'submission', 'status')},
        ),
    ]
