# Generated by Django 5.2.6 on 2026-03-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_text', models.TextField(default="Welcome to the University Extension Services Office (UESO). We are dedicated to fostering community engagement and extending the university's knowledge and resources to serve society.")),
                ('vision_text', models.TextField(default='To be a leading center of excellence in university extension services, creating meaningful partnerships between the academe and the community for sustainable development.')),
                ('mission_text', models.TextField(default='To deliver innovative extension programs and services that address community needs, promote social responsibility, and contribute to nation-building through collaborative partnerships and knowledge sharing.')),
                ('thrust_text', models.TextField(default='Our strategic thrust focuses on community empowerment, sustainable development, technology transfer, and capacity building to create lasting positive impact in the communities we serve.')),
                ('leadership_description', models.TextField(default='Our leadership team is committed to excellence in extension services, guided by principles of integrity, innovation, and inclusive development. We work collaboratively to ensure that university resources reach and benefit the wider community.')),
                ('director_name', models.CharField(blank=True, default='Dr. Liezl F. Tangonan', max_length=255, null=True)),
                ('director_image', models.ImageField(blank=True, default='faker/image.png', null=True, upload_to='about_us/director/')),
                ('org_chart_image', models.ImageField(blank=True, default='faker/UESO ORG CHART.png', null=True, upload_to='about_us/org_chart/')),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
