# Generated by Django 5.2.6 on 2026-03-16 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about_us', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aboutus_edits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aboutus',
            index=models.Index(fields=['-edited_at'], name='aboutus_edit_idx'),
        ),
    ]
