# Generated by Django 5.2.6 on 2025-12-05 12:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import system.utils.file_validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Campuses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(null=True, upload_to='colleges/logos/', validators=[system.utils.file_validators.validate_image_size])),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.campus')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('given_name', models.CharField(max_length=150)),
                ('middle_initial', models.CharField(blank=True, max_length=1, null=True)),
                ('last_name', models.CharField(max_length=150)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_no', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('FACULTY', 'Faculty'), ('IMPLEMENTER', 'Implementer'), ('CLIENT', 'Client'), ('UESO', 'UESO'), ('COORDINATOR', 'College Coordinator'), ('DEAN', 'College Dean'), ('PROGRAM_HEAD', 'Program Head'), ('DIRECTOR', 'Director of Extension'), ('VP', 'Vice President')], max_length=50)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('expertise', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('is_expert', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='users/profile_pictures/', validators=[system.utils.file_validators.validate_image_size])),
                ('bio', models.TextField(blank=True, null=True)),
                ('preferred_id', models.CharField(blank=True, choices=[('PASSPORT', 'Passport'), ('DRIVERS_LICENSE', "Driver's License"), ('UMID', 'UMID'), ('SSS', 'SSS'), ('GSIS', 'GSIS'), ('PRC', 'PRC'), ('OTHERS', 'Others')], max_length=50, null=True)),
                ('valid_id', models.ImageField(blank=True, null=True, upload_to='users/valid_ids/', validators=[system.utils.file_validators.validate_image_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_users', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.college')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserRoleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('FACULTY', 'Faculty'), ('IMPLEMENTER', 'Implementer'), ('CLIENT', 'Client'), ('UESO', 'UESO'), ('COORDINATOR', 'College Coordinator'), ('DEAN', 'College Dean'), ('PROGRAM_HEAD', 'Program Head'), ('DIRECTOR', 'Director of Extension'), ('VP', 'Vice President')], max_length=50)),
                ('data_snapshot', models.JSONField(default=dict)),
                ('ended_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_changes_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role History',
                'verbose_name_plural': 'User Role Histories',
                'ordering': ['-ended_at'],
            },
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['campus'], name='college_campus_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['name'], name='college_name_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', '-created_at'], name='user_role_created_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_confirmed'], name='user_role_confirmed_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['college', 'role'], name='user_college_role_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['college', '-created_at'], name='user_college_created_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_expert', 'role'], name='user_expert_role_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_expert', 'college'], name='user_expert_college_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'is_confirmed'], name='user_active_conf_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_confirmed', 'role'], name='user_conf_role_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_name', 'given_name'], name='user_name_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_by', '-created_at'], name='user_creator_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-created_at'], name='user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'college', 'is_confirmed'], name='user_role_col_conf_idx'),
        ),
    ]
