# Generated by Django 5.2.6 on 2026-03-16 07:44

import system.utils.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, help_text='End time of the meeting', null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('notes_attachment', models.FileField(blank=True, help_text='Optional file attachment for meeting notes', null=True, upload_to='meeting_attachments/', validators=[system.utils.file_validators.validate_file_size])),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
            ],
            options={
                'verbose_name': 'Meeting Event',
                'verbose_name_plural': 'Meeting Events',
                'ordering': ['datetime'],
            },
        ),
    ]
