# Generated by Django 5.2.6 on 2026-03-16 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_calendar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingevent',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meeting_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingevent',
            name='participants',
            field=models.ManyToManyField(related_name='meeting_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingevent',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_meeting_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='meetingevent',
            index=models.Index(fields=['status', 'datetime'], name='meeting_sched_date_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingevent',
            index=models.Index(fields=['datetime'], name='meeting_datetime_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingevent',
            index=models.Index(fields=['-created_at'], name='meeting_created_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingevent',
            index=models.Index(fields=['created_by', '-created_at'], name='meeting_creator_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingevent',
            index=models.Index(fields=['status', '-datetime'], name='meeting_status_idx'),
        ),
    ]
