# Generated by Django 5.2.6 on 2026-03-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('querystring', models.TextField(blank=True, default='')),
                ('type', models.CharField(choices=[('MANAGE_USER', 'Manage User'), ('PROJECT', 'Project')], max_length=50)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Export Request',
                'verbose_name_plural': 'Export Requests',
                'ordering': ['-date_submitted'],
            },
        ),
    ]
