# Generated by Django 5.2.6 on 2026-03-16 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exportrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_exports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exportrequest',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='exportrequest',
            index=models.Index(fields=['status', '-date_submitted'], name='exp_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='exportrequest',
            index=models.Index(fields=['submitted_by', '-date_submitted'], name='exp_submitter_idx'),
        ),
        migrations.AddIndex(
            model_name='exportrequest',
            index=models.Index(fields=['type', 'status'], name='exp_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='exportrequest',
            index=models.Index(fields=['status', 'reviewed_by'], name='exp_review_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='exportrequest',
            index=models.Index(fields=['date_submitted'], name='exp_date_idx'),
        ),
        migrations.AddIndex(
            model_name='exportrequest',
            index=models.Index(fields=['status', 'submitted_by'], name='exp_download_ready_idx'),
        ),
    ]
