# Generated by Django 5.2.6 on 2026-03-16 07:44

import system.utils.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Downloadable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='downloadables/files/', validators=[system.utils.file_validators.validate_file_size])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='downloadables/thumbnails/', validators=[system.utils.file_validators.validate_image_size])),
                ('available_for_non_users', models.BooleanField(default=False, help_text='Available for non-logged-in users')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('archived', 'Archived')], default='published', max_length=16)),
                ('file_type', models.CharField(blank=True, max_length=20)),
                ('is_submission_template', models.BooleanField(default=False, help_text='Used as a template for user submissions')),
                ('submission_type', models.CharField(choices=[('event', 'Event'), ('final', 'Final'), ('file', 'File')], default='file', max_length=10)),
            ],
            options={
                'verbose_name': 'Downloadable',
                'verbose_name_plural': 'Downloadables',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
