# Generated by Django 5.2.6 on 2026-03-16 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('downloadables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadable',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_downloadables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='downloadable',
            index=models.Index(fields=['status', '-uploaded_at'], name='dl_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadable',
            index=models.Index(fields=['status', 'available_for_non_users'], name='dl_public_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadable',
            index=models.Index(fields=['file_type', 'status'], name='dl_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadable',
            index=models.Index(fields=['is_submission_template', 'submission_type'], name='dl_template_type_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadable',
            index=models.Index(fields=['uploaded_by', '-uploaded_at'], name='dl_uploader_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadable',
            index=models.Index(fields=['status', 'file_type'], name='dl_browse_idx'),
        ),
    ]
