# Generated by Django 5.2.6 on 2026-03-16 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['-timestamp'], name='log_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['user', '-timestamp'], name='log_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['action', '-timestamp'], name='log_action_time_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['model', '-timestamp'], name='log_model_time_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['model', 'action', '-timestamp'], name='log_filter_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['is_notification', 'timestamp'], name='log_notif_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['model', 'object_id'], name='log_object_idx'),
        ),
    ]
