# Generated by Django 5.2.6 on 2026-03-16 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='published_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_announce', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='scheduled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_scheduled', 'scheduled_at', 'published_at'], name='ann_scheduler_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['published_at', 'archived'], name='ann_published_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['archived', '-published_at'], name='ann_active_list_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['title'], name='ann_title_search_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['published_at'], name='ann_pub_date_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['published_by', '-published_at'], name='ann_publisher_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['published_at', '-scheduled_at'], name='ann_draft_idx'),
        ),
    ]
