# Generated by Django 5.2.6 on 2026-03-16 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='concerned_colleges',
            field=models.ManyToManyField(related_name='agendas', to='users.college'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agendas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agenda',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_agendas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='agenda',
            index=models.Index(fields=['-created_at'], name='agenda_created_idx'),
        ),
        migrations.AddIndex(
            model_name='agenda',
            index=models.Index(fields=['created_by', '-created_at'], name='agenda_creator_idx'),
        ),
        migrations.AddIndex(
            model_name='agenda',
            index=models.Index(fields=['name'], name='agenda_name_idx'),
        ),
    ]
